version: '3'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/usr/src/Desktop/s_task3
    environment:
      - DB_HOST=dpg-cp552kocmk4c73est74g-a
      - DB_NAME=techtrack_db
      - DB_USER=yountuan
      - DB_PASSWORD=1
      - TOKEN
    ports:
      - 8000:8000

    command:
      sh -c "python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 manage.py runserver 0.0.0.0:8000"

    depends_on:
      - pgdb

  pgdb:
    image: postgres:16.3
    environment:
      - POSTGRES_DB=techtrack_db
      - POSTGRES_USER=yountuan
      - POSTGRES_PASSWORD=1
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null